baseurl         = "https://upbeat-liskov-e8fe07.netlify.com"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Marky's Personal Blog"
  subtitle    = "Lifestyle Investing Coding Fitness"

  cover       = "Sunrise.jpg"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "faketryghost"
  fbName = "fakeghost"
  githubName = "eueung"

  logo = "" 
  orgName = "EM"
  orgWebsite = "https://www.telematika.org"
  orgDescription = "Here is a description placeholder for your org"

  author = "Mark Li"
  authorAvatar = "MarkLi.jpeg"
  authorLocation = " Sydney,NSW "
  authorWebsite = "https://realmarkli.com"  
  authorDescription = "Lifetime Learner"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Investing"
  url = "/tags/Investing/"
  weight = 100

[[menu.main]]
  name = "Coding"
  url = "/tags/Coding/"
  weight = 99

[[menu.main]]
  name = "Fitness"
  url = "/tags/Fitness/"
  weight = 99


[[menu.main]]
  name = "Google"
  url = "https://google.com/"
  weight = 95